/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: abot86 (https://sketchfab.com/abot86)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/oasis-b24242e28c4640c688cf7038df67ad95
title: Oasis
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import WaterShiftMaterial from "../shaders/WaterShiftMaterial";
import { extend, useFrame } from "@react-three/fiber";

extend({ WaterShiftMaterial });

export default function Model({ ...props }) {
  const group = useRef();
  const waterRef = useRef();

  const { nodes, materials } = useGLTF("/oasis.gltf");

  useFrame((state) => {
    waterRef.current.material.uniforms.time.value = state.clock.elapsedTime;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={10}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.002"]}
              receiveShadow
            />
          </group>
          {/** --------- Water ---------*/}
          <group
            position={[-0.5, 4.45, 0.35]}
            rotation={[0, 0.43, 0]}
            scale={14.12}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              ref={waterRef}
              castShadow
              receiveShadow
            >
              <waterShiftMaterial
                key={WaterShiftMaterial.key}
                color="hotpink"
                time={1}
                wireframe={false}
              />
            </mesh>
          </group>
          {/** --------- End: Water ---------*/}
          <group position={[7.16, -10.36, -6.22]} scale={[3.3, 2.57, 3.3]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Material.003"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[7.89, -9.02, -6.24]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-3.85, 3.85, 3.85]}
          >
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Material.001"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[1.77, 3.67, -2.14]}
            rotation={[-0.03, 0.79, -0.11]}
            scale={[0.13, 0.19, 0.14]}
          >
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.Wood}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[2.4, 8.03, -2.53]} scale={0.16}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[2.1, 8.06, -2.35]} scale={0.15}>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[1.87, 8.08, -2.68]} scale={0.13}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[2.17, 8.03, -2.87]} scale={0.13}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[3.14, 7.88, -1.1]}
            rotation={[-0.38, 0.03, 0.07]}
            scale={1.68}
          >
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials["Material.005"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[3.14, 7.88, -1.1]}
            rotation={[-0.08, -1.03, -0.2]}
            scale={1.74}
          >
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials["Material.005"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[3.14, 7.88, -1.1]}
            rotation={[2.67, -0.71, 2.67]}
            scale={2.13}
          >
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials["Material.005"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[3.14, 7.88, -1.1]}
            rotation={[-3.08, 0.93, 3.11]}
            scale={2.13}
          >
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials["Material.005"]}
              castShadow
              receiveShadow
            />
          </group>
          <group
            position={[3.13, 7.36, -1.25]}
            rotation={[0.31, 1.2, -0.11]}
            scale={1.94}
          >
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["Material.005"]}
              castShadow
              receiveShadow
            />
          </group>
          {/* <group position={[-7.03, 12.34, -10.58]} scale={2.4}>
            <mesh geometry={nodes.Object_32.geometry} material={materials['Material.008']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-0.42, 12.42, 3.54]} rotation={[0, 0.66, 0]} scale={0.93}>
            <mesh geometry={nodes.Object_34.geometry} material={materials['Material.009']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[1.62, 10.59, 5.94]} rotation={[0, 0.12, 0]} scale={0.74}>
            <mesh geometry={nodes.Object_36.geometry} material={materials['Material.009']} castShadow receiveShadow/>
          </group> */}
          <group position={[3.91, 4.69, -0.91]} scale={0.26}>
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[3.97, 4.71, -0.08]} scale={0.31}>
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[4.31, 4.64, 0.78]} scale={0.39}>
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[5.09, 4.46, 1.57]} scale={0.52}>
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[1.61, 6.87, -2.87]} scale={0.13}>
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[1.39, 6.91, -2.65]} scale={0.15}>
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials.Material}
              castShadow
              receiveShadow
            />
          </group>
          {/* <group position={[-3, -0.68, -11.25]} rotation={[0, -0.15, 0]} scale={1.58}>
            <mesh geometry={nodes.Object_50.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[3.95, -2.81, -11.34]} scale={1.32}>
            <mesh geometry={nodes.Object_52.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-9.36, 1.32, -8.26]} rotation={[0, 0.33, 0]} scale={1.28}>
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-12.28, 3.32, -4.04]} rotation={[0, 0.36, 0]} scale={1.54}>
            <mesh geometry={nodes.Object_56.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-12.6, 5.45, 3.13]} rotation={[0, -0.11, 0]} scale={1.75}>
            <mesh geometry={nodes.Object_58.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-9.8, 6.98, 8.39]} rotation={[Math.PI, -1.25, Math.PI]} scale={1.64}>
            <mesh geometry={nodes.Object_60.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[-3.54, 5.14, 12.23]} rotation={[0, 0.74, 0]} scale={2.03}>
            <mesh geometry={nodes.Object_62.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[4.38, 2.98, 11.46]} rotation={[0, -0.85, 0]} scale={1.69}>
            <mesh geometry={nodes.Object_64.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[10.37, 1.46, 7.4]} rotation={[0, -0.55, 0]} scale={1.43}>
            <mesh geometry={nodes.Object_66.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          {/* <group position={[13.04, -1.61, -0.55]} rotation={[0, 0.48, 0]} scale={1.71}>
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.012']} castShadow receiveShadow/>
          </group> */}
          <group position={[7.07, -8.79, -5.72]} scale={0.74}>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
          <group position={[7.1, -8.81, -7.04]} scale={0.33}>
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials["Material.010"]}
              castShadow
              receiveShadow
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oasis.gltf");
