/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/three";

export default function Model({ ...props }) {
  const [hoverBuilding, setHoverBuilding] = useState(false);
  const buildingRef = useRef();
  const group = useRef();
  const { nodes, materials } = useGLTF("/toureasttest.gltf");

  const [{ y }] = useSpring(
    {
      y: Number(hoverBuilding),
      config: { mass: 1, tension: 120, friction: 14, precision: 0.002 },
    },
    [hoverBuilding]
  );

  useEffect(() => {
    void (document.body.style.cursor = hoverBuilding ? "pointer" : "auto");
  }, [hoverBuilding]);

  // Interpolations
  const floatPosY = y.to([0, 1], [0, 20]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Объект_Куб_1_15119.geometry}
        material={materials["Материал.054"]}
        position={[-148.42, -175.42, -266.68]}
        scale={3}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1222.geometry}
        material={materials["Материал.054"]}
        position={[-144.26, -166.38, -154.55]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["default"]}
        position={[-5.86, 16.95, 588.88]}
        scale={[1, 0.9, 1]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1002.geometry}
        material={materials["Материал.054"]}
        position={[-111.23, -166.38, -138.91]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[6.13, 7.35, 2.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1005.geometry}
        material={materials["Материал.054"]}
        position={[-65, -175.42, -305.8]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[3, 3, 4.56]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1006.geometry}
        material={materials["Материал.054"]}
        position={[-69.81, -166.38, -175.3]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[6.13, 7.35, 2.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1007.geometry}
        material={materials["Материал.054"]}
        position={[87.93, -175.42, -244.59]}
        scale={3}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1008.geometry}
        material={materials["Материал.054"]}
        position={[63.43, -179.47, -269.68]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1009.geometry}
        material={materials["Материал.054"]}
        position={[107.13, -175.42, -247.76]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[3, 3, 4.56]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1010.geometry}
        material={materials["Материал.054"]}
        position={[139.05, -179.47, -169.38]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[6.13, 7.35, 2.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1016.geometry}
        material={materials["Материал.054"]}
        position={[-77.24, -166.38, -95.53]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1019.geometry}
        material={materials["Материал.054"]}
        position={[-128.15, -175.42, -137.15]}
        scale={3}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1020.geometry}
        material={materials["Материал.054"]}
        position={[-150.72, -166.38, -67.44]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1023.geometry}
        material={materials["Материал.054"]}
        position={[149.86, -153.8, -240.92]}
        rotation={[0, -0.91, 0]}
        scale={[9.86, 9.85, 14.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1024.geometry}
        material={materials["Материал.054"]}
        position={[-173.14, -154.55, -123.27]}
        rotation={[0, -0.63, 0]}
        scale={[19.5, 23.4, 6.24]}
        receiveShadow
        castShadow
      />
      {/* Hover building test*/}
      <a.group position-y={floatPosY}>
        <mesh
          ref={buildingRef}
          geometry={nodes.Объект_Куб_1_1025.geometry}
          material={materials["Материал.054"]}
          position={[-102.46, -147.05, -222.21]}
          rotation={[Math.PI, -0.55, Math.PI]}
          scale={[7.84, 7.84, 11.92]}
          onPointerOver={() => setHoverBuilding(true)}
          onPointerOut={() => setHoverBuilding(false)}
          receiveShadow
          castShadow
        />
      </a.group>

      {/* Hover building test*/}
      <mesh
        geometry={nodes.Объект_Куб_1_1034.geometry}
        material={materials["Материал.054"]}
        position={[180.84, -154.55, -60.16]}
        rotation={[Math.PI, -0.83, Math.PI]}
        scale={[19.5, 23.4, 6.24]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1013.geometry}
        material={materials["Материал.054"]}
        position={[-44.99, -179.47, -271.5]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1014.geometry}
        material={materials["Материал.054"]}
        position={[-11.97, -179.47, -255.86]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[6.13, 7.35, 2.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1018.geometry}
        material={materials["Материал.054"]}
        position={[29.45, -179.47, -292.25]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[6.13, 7.35, 2.98]}
        receiveShadow
        castShadow
      />
      <mesh
        geometry={nodes.Объект_Куб_1_1022.geometry}
        material={materials["Материал.054"]}
        position={[22.03, -179.47, -212.48]}
        scale={[6.12, 7.35, 1.96]}
        receiveShadow
        castShadow
      />
      <group position={[0, -757.55, -149.24]} scale={[10.8, 9, 10.8]}>
        <mesh
          geometry={nodes.Mesh005.geometry}
          material={materials.blinn2}
          receiveShadow
          castShadow
        />
        <mesh
          geometry={nodes.Mesh005_1.geometry}
          material={materials.blinn1}
          receiveShadow
        />
      </group>
      <mesh
        geometry={nodes.GardensOnTheBay002.geometry}
        material={materials.blinn1}
        position={[0, -153.75, -149.24]}
        scale={[10.8, 9, 10.8]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/toureasttest.gltf");
